### ISSUE TITLE
bug; Invalid bind parameter value on "file" value

### ISSUE THREAD

**Issue by antokara** [triAGENS/ArangoDB-PHP#176]
I have an AQL that Binds a value to Filter an Attribute that matches the "file" value.
The problem is that the code here:
https://github.com/triAGENS/ArangoDB-PHP/blob/master/lib/triagens/ArangoDb/ValueValidator.php#L44

More specifically the part
```
is_callable($value)
```

returns true on a string containing the word "file" because it is also a php function.
please note that my bind variable has been explicitly defined as string with
```
$variable=strval($variable);
```
prior binding.

Is this intended? if not, perhaps the php gettype function
http://php.net/manual/en/function.gettype.php
could help/replace the above line? not sure why this check is being made there.

I can successfully bind and execute an AQL with the 'file' value with arangosh/http/etc.

**Comment by antokara** [comment]
Ok just tested it and it works, thanks for the light speed fix.
If possible, please apply to the 2.3.x branch also, thanks!

**Comment by jsteemann** [comment]
Thanks for the hint. The behavior was of course unintentional.
It should have been fixed now in the 2.3, 2.4 and devel branches of the driver. The should also be new tags.

**Comment by antokara** [comment]
Did a composer update with require "triagens/arangodb": "2.3.x-dev" but did not get it.

**Comment by antokara** [comment]
update, just got the 2.3.x thanks!
